language: ruby
rvm:
- 2.3.4
services:
- postgresql
bundler_args: "--without development --deployment"
cache: bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rake test
deploy:
  provider: heroku
  api_key:
    secure: oYbqe1jbI6EL7QqUzsINV05pgMHB4vlBLNvoFpT3hQ754TP8E4JJF41TqumDKbgMaRL4oQZt9O1MnKuBUUa4Pjmyd/VKAENjWOjz6o4IrGoWaKHd1KpgZ539YPBh1WWmYu7PxrLm8QUMApefb8wRYi8lBmKo03LwJXDQ2lctKGghlAjAmPBS1tFkCNXYXXBbQyQPU4P5ykzKZFK+7jvx3lLbK6SpUMb6gzf5lNOTp3OV2jZzUyeeii6a8zaQzTrMqsDTj7sKCd2qbZ6LiOjH6NZRR++3Jc+8hh+5dhTZqB4D0rpo8RU4nb1WqhyR+XWHJBn4x7ZahdKQfZKMlcwtsV3m4/pw/xmxhjcU8FQDVu3rmT0nYaO5LrMPL+61hxnT8VXqmJhe83CTNgXp60Ka0EQRhXVDIJorEHLJPXMvyP0OntLbAJcETxR+TD3Z1lDbemuH5K6oKHK2LaThpQ7SjxW9hsJZJUYoIpTlFS6KIQ2o7fFZtkKqvyqjYblA7qPicDvfOZsiAeVRVvpaO2GRIm6uflx583cMfbRGK1Z9x/yvr4bDElZcAsBimz6NkA7KFrPLN0IOaFDyEsCSeAVnOYjwdqaindTXsfZZ5ASsRKdr6VdQmFPViuHvaWioh+ue2s/dL6hETFyxf2CIIkaebm59g1b0wY9iTssB7jectVI=
  app: coderdojo-konan-jp-rails
  on:
    repo: CoderDojo-Konan-Okayama/coderdojo-konan.jp
secure: "IGayG45cTSLS3l6abLX5sWVZA7vhxNzWv0WJSUdClrOzgPUMu/DBP8zFVkqAuFckjaJFAIPKk0Jhz196WLJ8UkYAEk8JfsQpilkD0YQ1Npf1XAc+Kqnva/pXgKW03jpZ39Gn5RdxgFSIgg6i+2JCJjAShVqbQFIOt/bnYEmtKkJU982MQ2wpL7oXnXAA9wVgj2toRUi/RQX3e6E/gp5ImS30VOWiYVdzlDZ1tZn5aNnlf+TKOD9382dezzpn6YG1vqdx5iWmkXVgD8wNpAre1/unA4pTL981tMscg4rfBysMEwB0K68N8AUKCQINPDFK31HCYX77RTDt0Lz9OSumR8FXqsb5sI9bIzWlxO/AGe//63JzaNCGkm/kpexqCHsgwDkgKJegpIKYlcfejxryF62RaDCpBGu3fbLs096RZ1GfTG6hqtk6cB9aGV7L2B/lFiI8uJM/gdr2saGKpGB2ZkbX4O2HLAYXx3DNaCeAXPRrQcM/jV355n7jrSFrKhb5q6+DIy4lJ6KtXdT0as8yLZzdiIivamcJ++pwPxmbaVeb40hvJsLRGQ+7MsFBlQCC0vjfl5SvKJgIZi7qGUShPXraBsdu3LxgGvLrA7VOm5dTgQ0KGHFydyF5aEHxlpAw2j1BvL43vzgL7ulGnjB0ikZbRb9P+jQ7FsKLn0Q+Xbo="